# Generated by Django 4.0.3 on 2022-03-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('password', models.CharField(max_length=120, verbose_name='Password')),
                ('rol', models.CharField(choices=[(1, 'Looking for a job'), (2, 'Looking for an employee')], max_length=120, verbose_name='Rol')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
