# Generated by Django 4.0.3 on 2022-03-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='Apellido')),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
